-- full_schema_security_and_logic.sql
-- Extracted from full_schema_smart.sql: CREATE OR REPLACE FUNCTION, CREATE TRIGGER, CREATE POLICY (file order).
-- Generated by scripts/extract-security-and-logic.mjs

CREATE OR REPLACE FUNCTION public.has_role(_user_id UUID, _role app_role)
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.user_roles
        WHERE user_id = _user_id
        AND role = _role
    )
$$;

CREATE OR REPLACE FUNCTION public.is_manager(_user_id UUID)
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.user_roles
        WHERE user_id = _user_id
        AND role IN ('admin', 'fleet_manager')
    )
$$;

CREATE OR REPLACE FUNCTION public.is_own_driver_record(_user_id UUID, _driver_id UUID)
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.drivers
        WHERE id = _driver_id
        AND user_id = _user_id
    )
$$;

CREATE POLICY "Users can view their own roles"
    ON public.user_roles FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Admins can manage all roles"
    ON public.user_roles FOR ALL
    USING (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Users can view their own profile"
    ON public.profiles FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can update their own profile"
    ON public.profiles FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Managers can view all profiles"
    ON public.profiles FOR SELECT
    USING (public.is_manager(auth.uid()));

CREATE POLICY "Users can insert their own profile"
    ON public.profiles FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Authenticated users can view vehicles"
    ON public.vehicles FOR SELECT
    USING (auth.uid() IS NOT NULL);

CREATE POLICY "Managers can manage vehicles"
    ON public.vehicles FOR ALL
    USING (public.is_manager(auth.uid()));

CREATE POLICY "Managers can view all drivers"
    ON public.drivers FOR SELECT
    USING (public.is_manager(auth.uid()) OR public.has_role(auth.uid(), 'viewer'));

CREATE POLICY "Drivers can view own record"
    ON public.drivers FOR SELECT
    USING (user_id = auth.uid());

CREATE POLICY "Managers can manage drivers"
    ON public.drivers FOR ALL
    USING (public.is_manager(auth.uid()));

CREATE POLICY "Drivers can update own non-sensitive fields"
    ON public.drivers FOR UPDATE
    USING (user_id = auth.uid());

CREATE POLICY "Authenticated users can view maintenance logs"
    ON public.maintenance_logs FOR SELECT
    USING (auth.uid() IS NOT NULL);

CREATE POLICY "Managers can manage maintenance logs"
    ON public.maintenance_logs FOR ALL
    USING (public.is_manager(auth.uid()));

CREATE POLICY "Authenticated users can view handovers"
    ON public.vehicle_handovers FOR SELECT
    USING (auth.uid() IS NOT NULL);

CREATE POLICY "Managers can manage handovers"
    ON public.vehicle_handovers FOR ALL
    USING (public.is_manager(auth.uid()));

CREATE POLICY "Drivers can create handovers"
    ON public.vehicle_handovers FOR INSERT
    WITH CHECK (public.has_role(auth.uid(), 'driver'));

CREATE POLICY "Managers can view alerts"
    ON public.compliance_alerts FOR SELECT
    USING (public.is_manager(auth.uid()) OR public.has_role(auth.uid(), 'viewer'));

CREATE POLICY "Managers can manage alerts"
    ON public.compliance_alerts FOR ALL
    USING (public.is_manager(auth.uid()));

CREATE OR REPLACE FUNCTION public.update_vehicle_odometer()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    UPDATE public.vehicles
    SET current_odometer = NEW.odometer_reading,
        updated_at = now()
    WHERE id = NEW.vehicle_id
    AND current_odometer < NEW.odometer_reading;
    RETURN NEW;
END;
$$;

CREATE TRIGGER sync_vehicle_odometer
    AFTER INSERT ON public.maintenance_logs
    FOR EACH ROW
    EXECUTE FUNCTION public.update_vehicle_odometer();

CREATE OR REPLACE FUNCTION public.calculate_compliance_status(expiry_date DATE)
RETURNS compliance_status
LANGUAGE plpgsql
STABLE
AS $$
BEGIN
    IF expiry_date < CURRENT_DATE THEN
        RETURN 'expired';
    ELSIF expiry_date <= CURRENT_DATE + INTERVAL '30 days' THEN
        RETURN 'warning';
    ELSE
        RETURN 'valid';
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.update_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

CREATE TRIGGER update_profiles_updated_at
    BEFORE UPDATE ON public.profiles
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at();

CREATE TRIGGER update_vehicles_updated_at
    BEFORE UPDATE ON public.vehicles
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at();

CREATE TRIGGER update_drivers_updated_at
    BEFORE UPDATE ON public.drivers
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at();

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    INSERT INTO public.profiles (user_id, full_name, email)
    VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data->>'full_name', 'משתמש חדש'), NEW.email);
    
    -- Default role is viewer
    INSERT INTO public.user_roles (user_id, role)
    VALUES (NEW.id, 'viewer');
    
    RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_new_user();

CREATE OR REPLACE FUNCTION public.calculate_compliance_status(expiry_date DATE)
RETURNS compliance_status
LANGUAGE plpgsql
STABLE
SET search_path = public
AS $$
BEGIN
    IF expiry_date < CURRENT_DATE THEN
        RETURN 'expired';
    ELSIF expiry_date <= CURRENT_DATE + INTERVAL '30 days' THEN
        RETURN 'warning';
    ELSE
        RETURN 'valid';
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.update_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

CREATE POLICY "Managers can view vehicle documents"
ON storage.objects FOR SELECT
USING (bucket_id = 'vehicle-documents' AND public.is_manager(auth.uid()));

CREATE POLICY "Managers can upload vehicle documents"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'vehicle-documents' AND public.is_manager(auth.uid()));

CREATE POLICY "Managers can update vehicle documents"
ON storage.objects FOR UPDATE
USING (bucket_id = 'vehicle-documents' AND public.is_manager(auth.uid()));

CREATE POLICY "Managers can delete vehicle documents"
ON storage.objects FOR DELETE
USING (bucket_id = 'vehicle-documents' AND public.is_manager(auth.uid()));

CREATE POLICY "Managers can view driver documents"
ON storage.objects FOR SELECT
USING (bucket_id = 'driver-documents' AND public.is_manager(auth.uid()));

CREATE POLICY "Managers can upload driver documents"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'driver-documents' AND public.is_manager(auth.uid()));

CREATE POLICY "Managers can update driver documents"
ON storage.objects FOR UPDATE
USING (bucket_id = 'driver-documents' AND public.is_manager(auth.uid()));

CREATE POLICY "Managers can delete driver documents"
ON storage.objects FOR DELETE
USING (bucket_id = 'driver-documents' AND public.is_manager(auth.uid()));

CREATE POLICY "Authenticated users can view maintenance docs"
ON storage.objects FOR SELECT
USING (bucket_id = 'maintenance-documents' AND auth.uid() IS NOT NULL);

CREATE POLICY "Managers can upload maintenance docs"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'maintenance-documents' AND public.is_manager(auth.uid()));

CREATE POLICY "Managers can update maintenance docs"
ON storage.objects FOR UPDATE
USING (bucket_id = 'maintenance-documents' AND public.is_manager(auth.uid()));

CREATE POLICY "Managers can delete maintenance docs"
ON storage.objects FOR DELETE
USING (bucket_id = 'maintenance-documents' AND public.is_manager(auth.uid()));

CREATE POLICY "Authenticated users can view handover photos"
ON storage.objects FOR SELECT
USING (bucket_id = 'handover-photos' AND auth.uid() IS NOT NULL);

CREATE POLICY "Managers and drivers can upload handover photos"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'handover-photos' AND (public.is_manager(auth.uid()) OR public.has_role(auth.uid(), 'driver')));

CREATE POLICY "Managers can update handover photos"
ON storage.objects FOR UPDATE
USING (bucket_id = 'handover-photos' AND public.is_manager(auth.uid()));

CREATE POLICY "Managers can delete handover photos"
ON storage.objects FOR DELETE
USING (bucket_id = 'handover-photos' AND public.is_manager(auth.uid()));

CREATE POLICY "Managers can manage driver documents"
ON public.driver_documents
FOR ALL
USING (is_manager(auth.uid()));

CREATE POLICY "Drivers can view own documents"
ON public.driver_documents
FOR SELECT
USING (
    EXISTS (
        SELECT 1 FROM public.drivers 
        WHERE drivers.id = driver_documents.driver_id 
        AND drivers.user_id = auth.uid()
    )
);

CREATE POLICY "Authenticated users can view pricing data"
ON public.pricing_data
FOR SELECT
USING (auth.uid() IS NOT NULL);

CREATE POLICY "Managers can manage pricing data"
ON public.pricing_data
FOR ALL
USING (is_manager(auth.uid()));

CREATE TRIGGER update_pricing_data_updated_at
BEFORE UPDATE ON public.pricing_data
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at();

CREATE POLICY "Authenticated users can create drivers"
ON public.drivers
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated users can create vehicles"
ON public.vehicles
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated users can insert drivers"
ON public.drivers
FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Authenticated users can insert vehicles"
ON public.vehicles
FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Managers can manage all drivers"
ON public.drivers
FOR ALL
TO authenticated
USING (is_manager(auth.uid()));

CREATE POLICY "Managers can manage all vehicles"
ON public.vehicles
FOR ALL
TO authenticated
USING (is_manager(auth.uid()));

CREATE POLICY "Assigned drivers can update vehicle odometer"
ON public.vehicles
FOR UPDATE
TO authenticated
USING (
  assigned_driver_id IN (
    SELECT id FROM public.drivers WHERE user_id = auth.uid()
  )
);

CREATE POLICY "Authenticated users can create drivers"
ON public.drivers
FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Managers can manage all drivers"
ON public.drivers
FOR ALL
TO authenticated
USING (is_manager(auth.uid()));

CREATE POLICY "Users can view all drivers"
ON public.drivers
FOR SELECT
TO authenticated
USING (is_manager(auth.uid()) OR has_role(auth.uid(), 'viewer'::app_role));

CREATE POLICY "Drivers can view own record"
ON public.drivers
FOR SELECT
TO authenticated
USING (user_id = auth.uid());

CREATE POLICY "Drivers can update own record"
ON public.drivers
FOR UPDATE
TO authenticated
USING (user_id = auth.uid());

CREATE POLICY "Authenticated users can upload handover photos"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'handover-photos');

CREATE POLICY "Anyone can view handover photos"
ON storage.objects FOR SELECT
USING (bucket_id = 'handover-photos');

CREATE POLICY "Authenticated users can view assignments"
ON public.driver_vehicle_assignments FOR SELECT
TO authenticated
USING (auth.uid() IS NOT NULL);

CREATE POLICY "Managers can manage assignments"
ON public.driver_vehicle_assignments FOR ALL
TO authenticated
USING (is_manager(auth.uid()));

CREATE POLICY "Authenticated users can create handovers"
ON public.vehicle_handovers
FOR INSERT
WITH CHECK (auth.uid() IS NOT NULL);

CREATE OR REPLACE FUNCTION public.handle_handover_assignment()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF NEW.handover_type = 'delivery' THEN
        -- Assign driver to vehicle
        UPDATE public.vehicles
        SET assigned_driver_id = NEW.driver_id, updated_at = now()
        WHERE id = NEW.vehicle_id;
        
        -- Close previous assignment for this vehicle (if any)
        UPDATE public.driver_vehicle_assignments
        SET unassigned_at = now()
        WHERE vehicle_id = NEW.vehicle_id AND unassigned_at IS NULL;
        
        -- Create new assignment record
        INSERT INTO public.driver_vehicle_assignments (vehicle_id, driver_id, assigned_by, notes)
        VALUES (NEW.vehicle_id, NEW.driver_id, NEW.created_by, 'שיוך אוטומטי ממסירת רכב');
        
    ELSIF NEW.handover_type = 'return' THEN
        -- Unassign driver from vehicle
        UPDATE public.vehicles
        SET assigned_driver_id = NULL, updated_at = now()
        WHERE id = NEW.vehicle_id;
        
        -- Close assignment record
        UPDATE public.driver_vehicle_assignments
        SET unassigned_at = now()
        WHERE vehicle_id = NEW.vehicle_id AND driver_id = NEW.driver_id AND unassigned_at IS NULL;
    END IF;
    
    RETURN NEW;
END;
$$;

CREATE TRIGGER on_handover_created
AFTER INSERT ON public.vehicle_handovers
FOR EACH ROW
EXECUTE FUNCTION public.handle_handover_assignment();

CREATE POLICY "Authenticated users can view all drivers"
ON public.drivers
FOR SELECT
TO authenticated
USING (true);

CREATE OR REPLACE FUNCTION public.sync_vehicles_from_pricing()
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  updated_count integer := 0;
  total_vehicles integer := 0;
BEGIN
  SELECT count(*) INTO total_vehicles
  FROM vehicles
  WHERE manufacturer_code IS NOT NULL AND model_code IS NOT NULL;

  UPDATE vehicles v
  SET
    tax_year = p.usage_year,
    vehicle_type_code = p.vehicle_type_code,
    model_description = p.model_description,
    fuel_type = p.fuel_type,
    commercial_name = p.commercial_name,
    is_automatic = p.is_automatic,
    drive_type = p.drive_type,
    green_score = p.green_score,
    pollution_level = p.pollution_level,
    engine_volume = COALESCE(p.engine_volume_cc::text, v.engine_volume),
    weight = p.weight,
    list_price = p.list_price,
    adjusted_price = p.adjusted_price,
    tax_value_price = p.usage_value,
    effective_date = p.effective_date,
    updated_at = now()
  FROM pricing_data p
  WHERE v.manufacturer_code = p.manufacturer_code
    AND v.model_code = p.model_code
    AND v.year = p.registration_year
    AND v.manufacturer_code IS NOT NULL
    AND v.model_code IS NOT NULL;

  GET DIAGNOSTICS updated_count = ROW_COUNT;

  RETURN json_build_object('updated', updated_count, 'total', total_vehicles);
END;
$$;

CREATE POLICY "Authenticated users can view pricing data"
  ON public.pricing_data FOR SELECT
  TO authenticated
  USING (auth.uid() IS NOT NULL);

CREATE POLICY "Managers can manage pricing data"
  ON public.pricing_data FOR ALL
  TO authenticated
  USING (is_manager(auth.uid()))
  WITH CHECK (is_manager(auth.uid()));

CREATE POLICY "Authenticated users can create drivers"
  ON public.drivers FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Managers can manage all drivers"
  ON public.drivers FOR ALL
  TO authenticated
  USING (is_manager(auth.uid()))
  WITH CHECK (is_manager(auth.uid()));

CREATE POLICY "Users can view all drivers"
  ON public.drivers FOR SELECT
  TO authenticated
  USING (is_manager(auth.uid()) OR has_role(auth.uid(), 'viewer'::app_role));

CREATE POLICY "Drivers can view own record"
  ON public.drivers FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

CREATE POLICY "Drivers can update own record"
  ON public.drivers FOR UPDATE
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE POLICY "Authenticated users can insert pricing data"
  ON public.pricing_data
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated users can delete pricing data"
  ON public.pricing_data
  FOR DELETE
  TO authenticated
  USING (auth.uid() IS NOT NULL);

CREATE POLICY "Managers can manage complaints"
  ON public.procedure6_complaints
  FOR ALL
  USING (public.is_manager(auth.uid()))
  WITH CHECK (public.is_manager(auth.uid()));

CREATE POLICY "Viewers can read complaints"
  ON public.procedure6_complaints
  FOR SELECT
  USING (auth.uid() IS NOT NULL);

CREATE TRIGGER update_procedure6_complaints_updated_at
  BEFORE UPDATE ON public.procedure6_complaints
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

CREATE POLICY "Managers can manage vehicle documents"
ON public.vehicle_documents
FOR ALL
USING (is_manager(auth.uid()));

CREATE POLICY "Authenticated users can view vehicle documents"
ON public.vehicle_documents
FOR SELECT
USING (auth.uid() IS NOT NULL);

CREATE OR REPLACE FUNCTION public.handle_handover_assignment()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF NEW.handover_type = 'delivery' THEN
        IF COALESCE(NEW.assignment_mode, 'permanent') = 'permanent' THEN
            UPDATE public.vehicles
            SET assigned_driver_id = NEW.driver_id, updated_at = now()
            WHERE id = NEW.vehicle_id;

            UPDATE public.driver_vehicle_assignments
            SET unassigned_at = now()
            WHERE vehicle_id = NEW.vehicle_id AND unassigned_at IS NULL;

            INSERT INTO public.driver_vehicle_assignments (vehicle_id, driver_id, assigned_by, notes)
            VALUES (NEW.vehicle_id, NEW.driver_id, NEW.created_by, 'שיוך אוטומטי ממסירת רכב קבועה');
        ELSE
            INSERT INTO public.driver_vehicle_assignments (vehicle_id, driver_id, assigned_by, notes, unassigned_at)
            VALUES (NEW.vehicle_id, NEW.driver_id, NEW.created_by, 'מסירת רכב חליפי (ללא שיוך קבוע)', now());
        END IF;

    ELSIF NEW.handover_type = 'return' THEN
        UPDATE public.vehicles
        SET assigned_driver_id = NULL, updated_at = now()
        WHERE id = NEW.vehicle_id;

        UPDATE public.driver_vehicle_assignments
        SET unassigned_at = now()
        WHERE vehicle_id = NEW.vehicle_id AND driver_id = NEW.driver_id AND unassigned_at IS NULL;
    END IF;

    RETURN NEW;
END;
$$;

CREATE POLICY "Authenticated users can view vehicle documents storage"
ON storage.objects FOR SELECT
USING (bucket_id = 'vehicle-documents' AND auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated users can upload vehicle documents storage"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'vehicle-documents' AND auth.uid() IS NOT NULL);

CREATE POLICY "Managers can update vehicle documents storage"
ON storage.objects FOR UPDATE
USING (bucket_id = 'vehicle-documents' AND public.is_manager(auth.uid()));

CREATE POLICY "Managers can delete vehicle documents storage"
ON storage.objects FOR DELETE
USING (bucket_id = 'vehicle-documents' AND public.is_manager(auth.uid()));

create or replace function public.notify_send_handover_email()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform
    supabase_functions.http_request(
      'https://nlsdthcbvqgsfnlnbzcy.supabase.co/functions/v1/send-handover-email',
      'POST',
      '{"Content-Type": "application/json"}'::jsonb,
      jsonb_build_object(
        'type',       TG_OP,
        'table',      TG_TABLE_NAME,
        'schema',     TG_TABLE_SCHEMA,
        'record',     row_to_json(NEW),
        'old_record', null
      ),
      '10000'   -- timeout ms
    );
  return NEW;
end;
$$;

create trigger on_driver_document_inserted
  after insert on public.driver_documents
  for each row
  execute function public.notify_send_handover_email();

create or replace function public.set_system_settings_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger trg_system_settings_updated_at
  before update on public.system_settings
  for each row execute function public.set_system_settings_updated_at();

create policy "authenticated can select system_settings"
  on public.system_settings for select
  to authenticated using (true);

create policy "authenticated can upsert system_settings"
  on public.system_settings for all
  to authenticated using (true) with check (true);

CREATE POLICY "vehicle_documents_select_authenticated"
ON storage.objects FOR SELECT
USING (bucket_id = 'vehicle-documents' AND auth.uid() IS NOT NULL);

CREATE POLICY "vehicle_documents_insert_authenticated"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'vehicle-documents' AND auth.uid() IS NOT NULL);

CREATE POLICY "authenticated read org settings"
  ON public.organization_settings FOR SELECT
  TO authenticated USING (true);

CREATE POLICY "authenticated upsert org settings"
  ON public.organization_settings FOR ALL
  TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "authenticated read ui_customization"
  ON public.ui_customization FOR SELECT TO authenticated USING (true);

CREATE POLICY "authenticated write ui_customization"
  ON public.ui_customization FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "authenticated read org_documents"
  ON public.org_documents FOR SELECT TO authenticated USING (true);

CREATE POLICY "authenticated write org_documents"
  ON public.org_documents FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "auth read vehicle_expenses"  ON public.vehicle_expenses FOR SELECT TO authenticated USING (true);

CREATE POLICY "auth write vehicle_expenses" ON public.vehicle_expenses FOR ALL    TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "auth read vehicle_incidents"  ON public.vehicle_incidents FOR SELECT TO authenticated USING (true);

CREATE POLICY "auth write vehicle_incidents" ON public.vehicle_incidents FOR ALL    TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Authenticated users manage family members"
  ON driver_family_members FOR ALL
  USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users manage driver incidents"
  ON driver_incidents FOR ALL
  USING (auth.role() = 'authenticated');

create or replace function public.notify_send_handover_email()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  has_http_request boolean;
begin
  has_http_request := to_regprocedure('supabase_functions.http_request(text,text,jsonb,jsonb,text)') is not null;

  if has_http_request then
    perform
      supabase_functions.http_request(
        'https://hojopkvnajvexnwolyeu.supabase.co/functions/v1/send-handover-email',
        'POST',
        '{"Content-Type": "application/json"}'::jsonb,
        jsonb_build_object(
          'type', TG_OP,
          'table', TG_TABLE_NAME,
          'schema', TG_TABLE_SCHEMA,
          'record', row_to_json(NEW),
          'old_record', null
        ),
        '10000'
      );
  end if;

  return NEW;
exception
  when others then
    -- Never block INSERT into driver_documents due to webhook plumbing.
    raise notice 'notify_send_handover_email skipped: %', SQLERRM;
    return NEW;
end;
$$;

CREATE POLICY "Authenticated users can update drivers"
ON public.drivers
FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

CREATE OR REPLACE FUNCTION public.sync_assignment_from_handover(p_handover_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  r record;
BEGIN
  SELECT vehicle_id, driver_id, handover_type, assignment_mode, created_by
  INTO r
  FROM public.vehicle_handovers
  WHERE id = p_handover_id;

  IF NOT FOUND THEN
    RETURN;
  END IF;

  -- החזרה: מנקה assigned_driver_id ברכב + סוגר כל שורות assignment פתוחות לרכב (מיד כמו אצל רועי)
  IF r.handover_type = 'return' THEN
    UPDATE public.vehicles
    SET assigned_driver_id = NULL, updated_at = now()
    WHERE id = r.vehicle_id;

    UPDATE public.driver_vehicle_assignments
    SET unassigned_at = now()
    WHERE vehicle_id = r.vehicle_id
      AND unassigned_at IS NULL;

    RETURN;
  END IF;

  -- מסירה קבועה: כמו הטריגר — שיוך נהג לרכב + שורת assignment אחת פעילה לרכב
  IF r.handover_type = 'delivery' AND r.driver_id IS NOT NULL
     AND COALESCE(r.assignment_mode, 'permanent') = 'permanent' THEN

    UPDATE public.vehicles
    SET assigned_driver_id = r.driver_id, updated_at = now()
    WHERE id = r.vehicle_id;

    UPDATE public.driver_vehicle_assignments
    SET unassigned_at = now()
    WHERE vehicle_id = r.vehicle_id
      AND unassigned_at IS NULL;

    INSERT INTO public.driver_vehicle_assignments (vehicle_id, driver_id, assigned_by, notes)
    VALUES (
      r.vehicle_id,
      r.driver_id,
      r.created_by,
      'שיוך אוטומטי ממסירה (סנכרון לאחר ארכוב)'
    );
    RETURN;
  END IF;

  -- מסירה חליפית: רק רישום היסטורי סגור מיד (ללא שיוך קבוע) — כמו בטריגר
  IF r.handover_type = 'delivery' AND r.driver_id IS NOT NULL
     AND COALESCE(r.assignment_mode, 'permanent') = 'replacement' THEN
    INSERT INTO public.driver_vehicle_assignments (
      vehicle_id, driver_id, assigned_by, notes, unassigned_at
    )
    VALUES (
      r.vehicle_id,
      r.driver_id,
      r.created_by,
      'מסירת רכב חליפי (סנכרון לאחר ארכוב)',
      now()
    );
  END IF;
END;
$$;

CREATE POLICY "org_invitations_select_own_org"
  ON public.org_invitations FOR SELECT
  TO authenticated
  USING (
    org_id IN (
      SELECT org_id FROM public.profiles WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "org_invitations_insert_own_org"
  ON public.org_invitations FOR INSERT
  TO authenticated
  WITH CHECK (
    org_id IN (
      SELECT org_id FROM public.profiles WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "org_invitations_delete_own_org"
  ON public.org_invitations FOR DELETE
  TO authenticated
  USING (
    org_id IN (
      SELECT org_id FROM public.profiles WHERE user_id = auth.uid()
    )
  );

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  inv_org_id uuid;
  inv_permissions jsonb;
BEGIN
    INSERT INTO public.profiles (user_id, full_name, email)
    VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data->>'full_name', 'משתמש חדש'), NEW.email);

    -- If this email was invited, assign org_id and permissions from the invitation (most recent by created_at).
    SELECT oi.org_id, oi.permissions
    INTO inv_org_id, inv_permissions
    FROM public.org_invitations oi
    WHERE lower(trim(oi.email)) = lower(trim(NEW.email))
    ORDER BY oi.created_at DESC
    LIMIT 1;

    IF inv_org_id IS NOT NULL THEN
      UPDATE public.profiles
      SET org_id = inv_org_id,
          permissions = COALESCE(inv_permissions, '{}'::jsonb)
      WHERE user_id = NEW.id;
    END IF;

    -- Default role is viewer
    INSERT INTO public.user_roles (user_id, role)
    VALUES (NEW.id, 'viewer');

    RETURN NEW;
END;
$$;

create or replace function public.handle_new_mileage_log()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  _payload jsonb;
  _edge_response jsonb;
begin
  _payload := jsonb_build_object(
    'type', 'INSERT',
    'table', TG_TABLE_NAME,
    'schema', TG_TABLE_SCHEMA,
    'record', row_to_json(NEW),
    'old_record', null
  );

  perform
    http((
      'POST',
      current_setting('app.settings.supabase_url', true) || '/functions/v1/send-mileage-notification',
      array[
        ('Content-Type', 'application/json')::http_header,
        ('Authorization', 'Bearer ' || current_setting('app.settings.service_role_key', true))::http_header
      ],
      'application/json',
      _payload
    ));

  return NEW;
end;
$$;

create trigger trg_mileage_logs_notify
after insert on public.mileage_logs
for each row
execute function public.handle_new_mileage_log();

CREATE POLICY "org_invitations_select_by_invitee_email"
  ON public.org_invitations FOR SELECT
  TO authenticated
  USING (
    lower(trim(email)) = (
      SELECT lower(trim(email)) FROM public.profiles WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "org_invitations_delete_by_invitee_email"
  ON public.org_invitations FOR DELETE
  TO authenticated
  USING (
    lower(trim(email)) = (
      SELECT lower(trim(email)) FROM public.profiles WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "org_members_select_own"
  ON public.org_members FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

CREATE POLICY "org_members_insert_own"
  ON public.org_members FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  inv_org_id uuid;
  inv_permissions jsonb;
BEGIN
    INSERT INTO public.profiles (user_id, full_name, email)
    VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data->>'full_name', 'משתמש חדש'), NEW.email);

    SELECT oi.org_id, oi.permissions
    INTO inv_org_id, inv_permissions
    FROM public.org_invitations oi
    WHERE lower(trim(oi.email)) = lower(trim(NEW.email))
    ORDER BY oi.created_at DESC
    LIMIT 1;

    IF inv_org_id IS NOT NULL THEN
      UPDATE public.profiles
      SET org_id = inv_org_id,
          permissions = COALESCE(inv_permissions, '{}'::jsonb)
      WHERE user_id = NEW.id;

      INSERT INTO public.org_members (user_id, org_id)
      VALUES (NEW.id, inv_org_id)
      ON CONFLICT (user_id, org_id) DO NOTHING;
    END IF;

    INSERT INTO public.user_roles (user_id, role)
    VALUES (NEW.id, 'viewer');

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  inv_org_id uuid;
  inv_permissions jsonb;
BEGIN
    INSERT INTO public.profiles (user_id, full_name, email)
    VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data->>'full_name', 'משתמש חדש'), NEW.email);

    SELECT oi.org_id, oi.permissions
    INTO inv_org_id, inv_permissions
    FROM public.org_invitations oi
    WHERE lower(trim(oi.email)) = lower(trim(NEW.email))
    ORDER BY oi.created_at DESC
    LIMIT 1;

    IF inv_org_id IS NOT NULL THEN
      UPDATE public.profiles
      SET org_id = inv_org_id,
          permissions = COALESCE(inv_permissions, '{}'::jsonb),
          status = 'active'
      WHERE user_id = NEW.id;

      INSERT INTO public.org_members (user_id, org_id)
      VALUES (NEW.id, inv_org_id)
      ON CONFLICT (user_id, org_id) DO NOTHING;
    END IF;

    INSERT INTO public.user_roles (user_id, role)
    VALUES (NEW.id, 'viewer');

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  inv_org_id uuid;
  inv_permissions jsonb;
BEGIN
    INSERT INTO public.profiles (user_id, full_name, email, status)
    VALUES (
      NEW.id,
      COALESCE(NEW.raw_user_meta_data->>'full_name', 'משתמש חדש'),
      NEW.email,
      'pending_approval'
    );

    SELECT oi.org_id, oi.permissions
    INTO inv_org_id, inv_permissions
    FROM public.org_invitations oi
    WHERE lower(trim(oi.email)) = lower(trim(NEW.email))
    ORDER BY oi.created_at DESC
    LIMIT 1;

    IF inv_org_id IS NOT NULL THEN
      UPDATE public.profiles
      SET org_id = inv_org_id,
          permissions = COALESCE(inv_permissions, '{}'::jsonb)
      WHERE user_id = NEW.id;

      INSERT INTO public.org_members (user_id, org_id)
      VALUES (NEW.id, inv_org_id)
      ON CONFLICT (user_id, org_id) DO NOTHING;
    END IF;

    INSERT INTO public.user_roles (user_id, role)
    VALUES (NEW.id, 'viewer');

    RETURN NEW;
END;
$$;

CREATE POLICY "profiles_update_same_org_team_manager"
  ON public.profiles FOR UPDATE
  TO authenticated
  USING (
    org_id IS NOT NULL
    AND EXISTS (
      SELECT 1 FROM public.profiles m
      WHERE m.id = auth.uid()
      AND m.org_id = profiles.org_id
      AND (
        public.is_manager(auth.uid())
        OR COALESCE((m.permissions ->> 'manage_team')::boolean, false) = true
      )
    )
  )
  WITH CHECK (
    org_id IS NOT NULL
    AND EXISTS (
      SELECT 1 FROM public.profiles m
      WHERE m.id = auth.uid()
      AND m.org_id = profiles.org_id
      AND (
        public.is_manager(auth.uid())
        OR COALESCE((m.permissions ->> 'manage_team')::boolean, false) = true
      )
    )
  );

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  inv_org_id uuid;
  inv_permissions jsonb;
  inv_parent uuid;
BEGIN
  INSERT INTO public.profiles (user_id, full_name, email, status)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', 'משתמש חדש'),
    NEW.email,
    'pending_approval'
  );

  SELECT oi.org_id, oi.permissions, oi.invited_by
  INTO inv_org_id, inv_permissions, inv_parent
  FROM public.org_invitations oi
  WHERE lower(trim(oi.email)) = lower(trim(NEW.email))
  ORDER BY oi.created_at DESC
  LIMIT 1;

  IF inv_org_id IS NOT NULL THEN
    UPDATE public.profiles
    SET org_id = inv_org_id,
        permissions = COALESCE(inv_permissions, '{}'::jsonb),
        parent_admin_id = inv_parent
    WHERE user_id = NEW.id;

    INSERT INTO public.org_members (user_id, org_id)
    VALUES (NEW.id, inv_org_id)
    ON CONFLICT (user_id, org_id) DO NOTHING;
  END IF;

  INSERT INTO public.user_roles (user_id, role)
  VALUES (NEW.id, 'viewer');

  RETURN NEW;
END;
$$;

CREATE POLICY "profiles_select_same_org_team_manager"
  ON public.profiles FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles m
      WHERE m.id = auth.uid()
      AND m.org_id IS NOT NULL
      AND profiles.org_id IS NOT NULL
      AND m.org_id = profiles.org_id
      AND (
        public.is_manager(auth.uid())
        OR COALESCE((m.permissions ->> 'manage_team')::boolean, false) = true
      )
    )
  );

CREATE POLICY "user_feature_overrides_own"
  ON public.user_feature_overrides
  FOR ALL
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "user_feature_overrides_same_org_staff"
  ON public.user_feature_overrides
  FOR ALL
  TO authenticated
  USING (
    (
      public.has_role(auth.uid(), 'admin'::public.app_role)
      OR public.has_role(auth.uid(), 'fleet_manager'::public.app_role)
    )
    AND EXISTS (
      SELECT 1
      FROM public.profiles me
      INNER JOIN public.profiles them ON them.id = user_feature_overrides.user_id
      WHERE me.id = auth.uid()
        AND me.org_id IS NOT NULL
        AND them.org_id = me.org_id
    )
  )
  WITH CHECK (
    (
      public.has_role(auth.uid(), 'admin'::public.app_role)
      OR public.has_role(auth.uid(), 'fleet_manager'::public.app_role)
    )
    AND EXISTS (
      SELECT 1
      FROM public.profiles me
      INNER JOIN public.profiles them ON them.id = user_feature_overrides.user_id
      WHERE me.id = auth.uid()
        AND me.org_id IS NOT NULL
        AND them.org_id = me.org_id
    )
  );

create policy "mileage_reports_select_authenticated"
on storage.objects for select
using (bucket_id = 'mileage-reports' and auth.uid() is not null);

create policy "mileage_reports_insert_authenticated"
on storage.objects for insert
with check (bucket_id = 'mileage-reports' and auth.uid() is not null);

create policy "mileage_reports_update_authenticated"
on storage.objects for update
using (bucket_id = 'mileage-reports' and auth.uid() is not null)
with check (bucket_id = 'mileage-reports' and auth.uid() is not null);

create policy "mileage_logs_insert_authenticated"
  on public.mileage_logs
  for insert
  to authenticated
  with check (
    auth.uid() is not null
    and user_id = auth.uid()
    and exists (
      select 1
      from public.vehicles v
      where v.id = vehicle_id
        and (
          (
            v.org_id is not null
            and exists (
              select 1
              from public.org_members om
              where om.org_id = v.org_id
                and om.user_id = auth.uid()
            )
          )
          or v.org_id is null
        )
    )
  );

create policy "mileage_logs_select_authenticated"
  on public.mileage_logs
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.vehicles v
      where v.id = vehicle_id
        and (
          (
            v.org_id is not null
            and exists (
              select 1
              from public.org_members om
              where om.org_id = v.org_id
                and om.user_id = auth.uid()
            )
          )
          or v.org_id is null
        )
    )
  );

create policy "mileage_reports_select_public_bucket"
on storage.objects
for select
using (bucket_id = 'mileage-reports');

CREATE OR REPLACE FUNCTION public.user_belongs_to_org(_user_id uuid, _org_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.profiles p
    WHERE p.id = _user_id
      AND p.org_id IS NOT NULL
      AND p.org_id = _org_id
  );
$$;

CREATE OR REPLACE FUNCTION public.can_edit_org_ui_settings(_user_id uuid, _org_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT public.user_belongs_to_org(_user_id, _org_id)
    AND (
      public.is_manager(_user_id)
      OR EXISTS (
        SELECT 1
        FROM public.profiles p
        WHERE p.id = _user_id
          AND (
            COALESCE((p.permissions ->> 'admin_access')::boolean, false)
            OR COALESCE((p.permissions ->> 'manage_team')::boolean, false)
          )
      )
    );
$$;

CREATE POLICY "ui_settings_select_org_member"
  ON public.ui_settings
  FOR SELECT
  TO authenticated
  USING (public.user_belongs_to_org(auth.uid(), org_id));

CREATE POLICY "ui_settings_insert_org_admin"
  ON public.ui_settings
  FOR INSERT
  TO authenticated
  WITH CHECK (public.can_edit_org_ui_settings(auth.uid(), org_id));

CREATE POLICY "ui_settings_update_org_admin"
  ON public.ui_settings
  FOR UPDATE
  TO authenticated
  USING (public.can_edit_org_ui_settings(auth.uid(), org_id))
  WITH CHECK (public.can_edit_org_ui_settings(auth.uid(), org_id));

CREATE POLICY "ui_settings_delete_org_admin"
  ON public.ui_settings
  FOR DELETE
  TO authenticated
  USING (public.can_edit_org_ui_settings(auth.uid(), org_id));

CREATE POLICY "authenticated can select system_settings"
  ON public.system_settings
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "authenticated can upsert system_settings"
  ON public.system_settings
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE OR REPLACE FUNCTION public.user_belongs_to_org(_user_id uuid, _org_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    _org_id IS NOT NULL
    AND (
      EXISTS (
        SELECT 1
        FROM public.profiles p
        WHERE p.id = _user_id
          AND p.org_id IS NOT NULL
          AND p.org_id = _org_id
      )
      OR EXISTS (
        SELECT 1
        FROM public.org_members m
        WHERE m.user_id = _user_id
          AND m.org_id = _org_id
      )
    );
$$;

CREATE OR REPLACE FUNCTION public.user_has_fleet_staff_privileges(_user_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    EXISTS (
      SELECT 1
      FROM public.user_roles ur
      WHERE ur.user_id = _user_id
        AND ur.role::text IN ('admin', 'fleet_manager')
    )
    OR EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = _user_id
        AND (
          COALESCE((p.permissions ->> 'admin_access')::boolean, false)
          OR COALESCE((p.permissions ->> 'manage_team')::boolean, false)
        )
    );
$$;

CREATE OR REPLACE FUNCTION public.can_org_admin_write(_user_id uuid, _org_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT CASE
    WHEN _org_id IS NULL THEN
      public.user_has_fleet_staff_privileges(_user_id)
    ELSE
      public.user_belongs_to_org(_user_id, _org_id)
      AND public.user_has_fleet_staff_privileges(_user_id)
  END;
$$;

CREATE POLICY "organizations_select_same_org"
        ON public.organizations FOR SELECT TO authenticated
        USING (public.user_belongs_to_org(auth.uid(), id));

CREATE POLICY "organizations_insert_org_admins"
        ON public.organizations FOR INSERT TO authenticated
        WITH CHECK (public.can_org_admin_write(auth.uid(), id));

CREATE POLICY "organizations_update_org_admins"
        ON public.organizations FOR UPDATE TO authenticated
        USING (public.can_org_admin_write(auth.uid(), id))
        WITH CHECK (public.can_org_admin_write(auth.uid(), id));

CREATE POLICY "organizations_delete_org_admins"
        ON public.organizations FOR DELETE TO authenticated
        USING (public.can_org_admin_write(auth.uid(), id));

CREATE POLICY "vehicles_select_org_scope"
      ON public.vehicles FOR SELECT TO authenticated
      USING (
        (org_id IS NULL OR public.user_belongs_to_org(auth.uid(), org_id))
        AND (managed_by_user_id IS NULL OR managed_by_user_id = auth.uid())
      );

CREATE POLICY "vehicles_insert_org_admins"
      ON public.vehicles FOR INSERT TO authenticated
      WITH CHECK (
        (org_id IS NOT NULL AND public.can_org_admin_write(auth.uid(), org_id))
        OR (org_id IS NULL AND public.can_org_admin_write(auth.uid(), NULL))
      );

CREATE POLICY "vehicles_update_org_admins"
      ON public.vehicles FOR UPDATE TO authenticated
      USING (
        (org_id IS NOT NULL AND public.can_org_admin_write(auth.uid(), org_id))
        OR (org_id IS NULL AND public.can_org_admin_write(auth.uid(), NULL))
      )
      WITH CHECK (
        (org_id IS NOT NULL AND public.can_org_admin_write(auth.uid(), org_id))
        OR (org_id IS NULL AND public.can_org_admin_write(auth.uid(), NULL))
      );

CREATE POLICY "vehicles_delete_org_admins"
      ON public.vehicles FOR DELETE TO authenticated
      USING (
        (org_id IS NOT NULL AND public.can_org_admin_write(auth.uid(), org_id))
        OR (org_id IS NULL AND public.can_org_admin_write(auth.uid(), NULL))
      );

CREATE POLICY "vehicles_update_assigned_driver_odometer"
      ON public.vehicles FOR UPDATE TO authenticated
      USING (
        assigned_driver_id IN (SELECT d.id FROM public.drivers d WHERE d.user_id = auth.uid())
        AND (org_id IS NULL OR public.user_belongs_to_org(auth.uid(), org_id))
      )
      WITH CHECK (
        assigned_driver_id IN (SELECT d.id FROM public.drivers d WHERE d.user_id = auth.uid())
        AND (org_id IS NULL OR public.user_belongs_to_org(auth.uid(), org_id))
      );

CREATE POLICY "drivers_select_org_scope"
      ON public.drivers FOR SELECT TO authenticated
      USING (
        (user_id IS NOT NULL AND user_id = auth.uid())
        OR (
          (org_id IS NULL OR public.user_belongs_to_org(auth.uid(), org_id))
          AND (managed_by_user_id IS NULL OR managed_by_user_id = auth.uid())
        )
        OR (
          EXISTS (
            SELECT 1
            FROM public.user_roles ur
            WHERE ur.user_id = auth.uid()
              AND ur.role::text = 'viewer'
          )
          AND (org_id IS NULL OR public.user_belongs_to_org(auth.uid(), org_id))
          AND (managed_by_user_id IS NULL OR managed_by_user_id = auth.uid())
        )
      );

CREATE POLICY "drivers_insert_org_admins"
      ON public.drivers FOR INSERT TO authenticated
      WITH CHECK (
        (org_id IS NOT NULL AND public.can_org_admin_write(auth.uid(), org_id))
        OR (org_id IS NULL AND public.can_org_admin_write(auth.uid(), NULL))
      );

CREATE POLICY "drivers_update_org_admins"
      ON public.drivers FOR UPDATE TO authenticated
      USING (
        (org_id IS NOT NULL AND public.can_org_admin_write(auth.uid(), org_id))
        OR (org_id IS NULL AND public.can_org_admin_write(auth.uid(), NULL))
      )
      WITH CHECK (
        (org_id IS NOT NULL AND public.can_org_admin_write(auth.uid(), org_id))
        OR (org_id IS NULL AND public.can_org_admin_write(auth.uid(), NULL))
      );

CREATE POLICY "drivers_update_own_linked_user"
      ON public.drivers FOR UPDATE TO authenticated
      USING (
        user_id IS NOT NULL
        AND user_id = auth.uid()
        AND (org_id IS NULL OR public.user_belongs_to_org(auth.uid(), org_id))
      )
      WITH CHECK (
        user_id IS NOT NULL
        AND user_id = auth.uid()
        AND (org_id IS NULL OR public.user_belongs_to_org(auth.uid(), org_id))
      );

CREATE POLICY "drivers_delete_org_admins"
      ON public.drivers FOR DELETE TO authenticated
      USING (
        (org_id IS NOT NULL AND public.can_org_admin_write(auth.uid(), org_id))
        OR (org_id IS NULL AND public.can_org_admin_write(auth.uid(), NULL))
      );

CREATE POLICY "org_documents_select_authenticated"
      ON public.org_documents FOR SELECT TO authenticated
      USING (auth.uid() IS NOT NULL);

CREATE POLICY "org_documents_insert_staff"
      ON public.org_documents FOR INSERT TO authenticated
      WITH CHECK (public.can_org_admin_write(auth.uid(), (SELECT p.org_id FROM public.profiles p WHERE p.id = auth.uid())));

CREATE POLICY "org_documents_update_staff"
      ON public.org_documents FOR UPDATE TO authenticated
      USING (public.can_org_admin_write(auth.uid(), (SELECT p.org_id FROM public.profiles p WHERE p.id = auth.uid())))
      WITH CHECK (public.can_org_admin_write(auth.uid(), (SELECT p.org_id FROM public.profiles p WHERE p.id = auth.uid())));

CREATE POLICY "org_documents_delete_staff"
      ON public.org_documents FOR DELETE TO authenticated
      USING (public.can_org_admin_write(auth.uid(), (SELECT p.org_id FROM public.profiles p WHERE p.id = auth.uid())));

CREATE POLICY "organization_settings_select_same_org"
          ON public.organization_settings FOR SELECT TO authenticated
          USING (
            organization_id IS NULL
            OR public.user_belongs_to_org(auth.uid(), organization_id)
          );

CREATE POLICY "organization_settings_insert_org_admins"
          ON public.organization_settings FOR INSERT TO authenticated
          WITH CHECK (
            organization_id IS NOT NULL
            AND public.can_org_admin_write(auth.uid(), organization_id)
          );

CREATE POLICY "organization_settings_update_org_admins"
          ON public.organization_settings FOR UPDATE TO authenticated
          USING (
            organization_id IS NOT NULL
            AND public.can_org_admin_write(auth.uid(), organization_id)
          )
          WITH CHECK (
            organization_id IS NOT NULL
            AND public.can_org_admin_write(auth.uid(), organization_id)
          );

CREATE POLICY "organization_settings_delete_org_admins"
          ON public.organization_settings FOR DELETE TO authenticated
          USING (
            organization_id IS NOT NULL
            AND public.can_org_admin_write(auth.uid(), organization_id)
          );

CREATE POLICY "organization_settings_select_authenticated"
          ON public.organization_settings FOR SELECT TO authenticated
          USING (auth.uid() IS NOT NULL);

CREATE POLICY "organization_settings_insert_staff"
          ON public.organization_settings FOR INSERT TO authenticated
          WITH CHECK (public.can_org_admin_write(auth.uid(), (SELECT org_id FROM public.profiles WHERE id = auth.uid())));

CREATE POLICY "organization_settings_update_staff"
          ON public.organization_settings FOR UPDATE TO authenticated
          USING (public.can_org_admin_write(auth.uid(), (SELECT org_id FROM public.profiles WHERE id = auth.uid())))
          WITH CHECK (public.can_org_admin_write(auth.uid(), (SELECT org_id FROM public.profiles WHERE id = auth.uid())));

CREATE POLICY "organization_settings_delete_staff"
          ON public.organization_settings FOR DELETE TO authenticated
          USING (public.can_org_admin_write(auth.uid(), (SELECT org_id FROM public.profiles WHERE id = auth.uid())));

CREATE POLICY "ui_customization_select_authenticated"
      ON public.ui_customization FOR SELECT TO authenticated
      USING (auth.uid() IS NOT NULL);

CREATE POLICY "ui_customization_insert_staff"
      ON public.ui_customization FOR INSERT TO authenticated
      WITH CHECK (public.can_org_admin_write(auth.uid(), (SELECT p.org_id FROM public.profiles p WHERE p.id = auth.uid())));

CREATE POLICY "ui_customization_update_staff"
      ON public.ui_customization FOR UPDATE TO authenticated
      USING (public.can_org_admin_write(auth.uid(), (SELECT p.org_id FROM public.profiles p WHERE p.id = auth.uid())))
      WITH CHECK (public.can_org_admin_write(auth.uid(), (SELECT p.org_id FROM public.profiles p WHERE p.id = auth.uid())));

CREATE POLICY "ui_customization_delete_staff"
      ON public.ui_customization FOR DELETE TO authenticated
      USING (public.can_org_admin_write(auth.uid(), (SELECT p.org_id FROM public.profiles p WHERE p.id = auth.uid())));

CREATE POLICY "feature_flags_select_authenticated"
      ON public.feature_flags FOR SELECT TO authenticated
      USING (auth.uid() IS NOT NULL);

CREATE POLICY "feature_flags_insert_staff"
      ON public.feature_flags FOR INSERT TO authenticated
      WITH CHECK (public.can_org_admin_write(auth.uid(), (SELECT p.org_id FROM public.profiles p WHERE p.id = auth.uid())));

CREATE POLICY "feature_flags_update_staff"
      ON public.feature_flags FOR UPDATE TO authenticated
      USING (public.can_org_admin_write(auth.uid(), (SELECT p.org_id FROM public.profiles p WHERE p.id = auth.uid())))
      WITH CHECK (public.can_org_admin_write(auth.uid(), (SELECT p.org_id FROM public.profiles p WHERE p.id = auth.uid())));

CREATE POLICY "feature_flags_delete_staff"
      ON public.feature_flags FOR DELETE TO authenticated
      USING (public.can_org_admin_write(auth.uid(), (SELECT p.org_id FROM public.profiles p WHERE p.id = auth.uid())));

CREATE POLICY "system_settings_insert_staff"
        ON public.system_settings FOR INSERT TO authenticated
        WITH CHECK (public.user_has_fleet_staff_privileges(auth.uid()));

CREATE POLICY "system_settings_update_staff"
        ON public.system_settings FOR UPDATE TO authenticated
        USING (public.user_has_fleet_staff_privileges(auth.uid()))
        WITH CHECK (public.user_has_fleet_staff_privileges(auth.uid()));

CREATE POLICY "system_settings_delete_staff"
        ON public.system_settings FOR DELETE TO authenticated
        USING (public.user_has_fleet_staff_privileges(auth.uid()));

CREATE POLICY "maintenance_logs_select_same_org"
      ON public.maintenance_logs FOR SELECT TO authenticated
      USING (
        EXISTS (
          SELECT 1
          FROM public.vehicles v
          WHERE v.id = maintenance_logs.vehicle_id
            AND (v.org_id IS NULL OR public.user_belongs_to_org(auth.uid(), v.org_id))
        )
      );

CREATE POLICY "maintenance_logs_insert_org_admins"
      ON public.maintenance_logs FOR INSERT TO authenticated
      WITH CHECK (
        EXISTS (
          SELECT 1
          FROM public.vehicles v
          WHERE v.id = maintenance_logs.vehicle_id
            AND public.can_org_admin_write(auth.uid(), v.org_id)
        )
      );

CREATE POLICY "maintenance_logs_update_org_admins"
      ON public.maintenance_logs FOR UPDATE TO authenticated
      USING (
        EXISTS (
          SELECT 1
          FROM public.vehicles v
          WHERE v.id = maintenance_logs.vehicle_id
            AND public.can_org_admin_write(auth.uid(), v.org_id)
        )
      )
      WITH CHECK (
        EXISTS (
          SELECT 1
          FROM public.vehicles v
          WHERE v.id = maintenance_logs.vehicle_id
            AND public.can_org_admin_write(auth.uid(), v.org_id)
        )
      );

CREATE POLICY "maintenance_logs_delete_org_admins"
      ON public.maintenance_logs FOR DELETE TO authenticated
      USING (
        EXISTS (
          SELECT 1
          FROM public.vehicles v
          WHERE v.id = maintenance_logs.vehicle_id
            AND public.can_org_admin_write(auth.uid(), v.org_id)
        )
      );

CREATE POLICY "vehicle_handovers_select_same_org"
      ON public.vehicle_handovers FOR SELECT TO authenticated
      USING (
        EXISTS (
          SELECT 1
          FROM public.vehicles v
          WHERE v.id = vehicle_handovers.vehicle_id
            AND (v.org_id IS NULL OR public.user_belongs_to_org(auth.uid(), v.org_id))
        )
      );

CREATE POLICY "vehicle_handovers_insert_org_participants"
      ON public.vehicle_handovers FOR INSERT TO authenticated
      WITH CHECK (
        EXISTS (
          SELECT 1
          FROM public.vehicles v
          WHERE v.id = vehicle_handovers.vehicle_id
            AND (v.org_id IS NULL OR public.user_belongs_to_org(auth.uid(), v.org_id))
            AND (
              EXISTS (
                SELECT 1
                FROM public.user_roles ur
                WHERE ur.user_id = auth.uid()
                  AND ur.role::text = 'driver'
              )
              OR public.can_org_admin_write(auth.uid(), v.org_id)
            )
        )
      );

CREATE POLICY "vehicle_handovers_update_org_admins"
      ON public.vehicle_handovers FOR UPDATE TO authenticated
      USING (
        EXISTS (
          SELECT 1
          FROM public.vehicles v
          WHERE v.id = vehicle_handovers.vehicle_id
            AND public.can_org_admin_write(auth.uid(), v.org_id)
        )
      )
      WITH CHECK (
        EXISTS (
          SELECT 1
          FROM public.vehicles v
          WHERE v.id = vehicle_handovers.vehicle_id
            AND public.can_org_admin_write(auth.uid(), v.org_id)
        )
      );

CREATE POLICY "vehicle_handovers_delete_org_admins"
      ON public.vehicle_handovers FOR DELETE TO authenticated
      USING (
        EXISTS (
          SELECT 1
          FROM public.vehicles v
          WHERE v.id = vehicle_handovers.vehicle_id
            AND public.can_org_admin_write(auth.uid(), v.org_id)
        )
      );

CREATE POLICY "compliance_alerts_select_same_org"
      ON public.compliance_alerts FOR SELECT TO authenticated
      USING (
        (
          entity_type = 'vehicle'
          AND EXISTS (
            SELECT 1
            FROM public.vehicles v
            WHERE v.id = compliance_alerts.entity_id
              AND (v.org_id IS NULL OR public.user_belongs_to_org(auth.uid(), v.org_id))
          )
        )
        OR (
          entity_type = 'driver'
          AND EXISTS (
            SELECT 1
            FROM public.drivers d
            WHERE d.id = compliance_alerts.entity_id
              AND (d.org_id IS NULL OR public.user_belongs_to_org(auth.uid(), d.org_id))
          )
        )
      );

CREATE POLICY "compliance_alerts_insert_org_admins"
      ON public.compliance_alerts FOR INSERT TO authenticated
      WITH CHECK (
        (
          entity_type = 'vehicle'
          AND EXISTS (
            SELECT 1
            FROM public.vehicles v
            WHERE v.id = compliance_alerts.entity_id
              AND public.can_org_admin_write(auth.uid(), v.org_id)
          )
        )
        OR (
          entity_type = 'driver'
          AND EXISTS (
            SELECT 1
            FROM public.drivers d
            WHERE d.id = compliance_alerts.entity_id
              AND public.can_org_admin_write(auth.uid(), d.org_id)
          )
        )
      );

CREATE POLICY "compliance_alerts_update_org_admins"
      ON public.compliance_alerts FOR UPDATE TO authenticated
      USING (
        (
          entity_type = 'vehicle'
          AND EXISTS (
            SELECT 1
            FROM public.vehicles v
            WHERE v.id = compliance_alerts.entity_id
              AND public.can_org_admin_write(auth.uid(), v.org_id)
          )
        )
        OR (
          entity_type = 'driver'
          AND EXISTS (
            SELECT 1
            FROM public.drivers d
            WHERE d.id = compliance_alerts.entity_id
              AND public.can_org_admin_write(auth.uid(), d.org_id)
          )
        )
      )
      WITH CHECK (
        (
          entity_type = 'vehicle'
          AND EXISTS (
            SELECT 1
            FROM public.vehicles v
            WHERE v.id = compliance_alerts.entity_id
              AND public.can_org_admin_write(auth.uid(), v.org_id)
          )
        )
        OR (
          entity_type = 'driver'
          AND EXISTS (
            SELECT 1
            FROM public.drivers d
            WHERE d.id = compliance_alerts.entity_id
              AND public.can_org_admin_write(auth.uid(), d.org_id)
          )
        )
      );

CREATE POLICY "compliance_alerts_delete_org_admins"
      ON public.compliance_alerts FOR DELETE TO authenticated
      USING (
        (
          entity_type = 'vehicle'
          AND EXISTS (
            SELECT 1
            FROM public.vehicles v
            WHERE v.id = compliance_alerts.entity_id
              AND public.can_org_admin_write(auth.uid(), v.org_id)
          )
        )
        OR (
          entity_type = 'driver'
          AND EXISTS (
            SELECT 1
            FROM public.drivers d
            WHERE d.id = compliance_alerts.entity_id
              AND public.can_org_admin_write(auth.uid(), d.org_id)
          )
        )
      );

CREATE POLICY "driver_documents_select_same_org"
      ON public.driver_documents FOR SELECT TO authenticated
      USING (
        EXISTS (
          SELECT 1
          FROM public.drivers d
          WHERE d.id = driver_documents.driver_id
            AND (
              (d.user_id IS NOT NULL AND d.user_id = auth.uid())
              OR (d.org_id IS NULL OR public.user_belongs_to_org(auth.uid(), d.org_id))
            )
        )
      );

CREATE POLICY "driver_documents_insert_org_admins"
      ON public.driver_documents FOR INSERT TO authenticated
      WITH CHECK (
        EXISTS (
          SELECT 1
          FROM public.drivers d
          WHERE d.id = driver_documents.driver_id
            AND public.can_org_admin_write(auth.uid(), d.org_id)
        )
      );

CREATE POLICY "driver_documents_update_org_admins"
      ON public.driver_documents FOR UPDATE TO authenticated
      USING (
        EXISTS (
          SELECT 1
          FROM public.drivers d
          WHERE d.id = driver_documents.driver_id
            AND public.can_org_admin_write(auth.uid(), d.org_id)
        )
      )
      WITH CHECK (
        EXISTS (
          SELECT 1
          FROM public.drivers d
          WHERE d.id = driver_documents.driver_id
            AND public.can_org_admin_write(auth.uid(), d.org_id)
        )
      );

CREATE POLICY "driver_documents_delete_org_admins"
      ON public.driver_documents FOR DELETE TO authenticated
      USING (
        EXISTS (
          SELECT 1
          FROM public.drivers d
          WHERE d.id = driver_documents.driver_id
            AND public.can_org_admin_write(auth.uid(), d.org_id)
        )
      );

CREATE POLICY "assignments_select_same_org"
      ON public.driver_vehicle_assignments FOR SELECT TO authenticated
      USING (
        EXISTS (
          SELECT 1
          FROM public.vehicles v
          WHERE v.id = driver_vehicle_assignments.vehicle_id
            AND (v.org_id IS NULL OR public.user_belongs_to_org(auth.uid(), v.org_id))
        )
      );

CREATE POLICY "assignments_insert_org_admins"
      ON public.driver_vehicle_assignments FOR INSERT TO authenticated
      WITH CHECK (
        EXISTS (
          SELECT 1
          FROM public.vehicles v
          WHERE v.id = driver_vehicle_assignments.vehicle_id
            AND public.can_org_admin_write(auth.uid(), v.org_id)
        )
      );

CREATE POLICY "assignments_update_org_admins"
      ON public.driver_vehicle_assignments FOR UPDATE TO authenticated
      USING (
        EXISTS (
          SELECT 1
          FROM public.vehicles v
          WHERE v.id = driver_vehicle_assignments.vehicle_id
            AND public.can_org_admin_write(auth.uid(), v.org_id)
        )
      )
      WITH CHECK (
        EXISTS (
          SELECT 1
          FROM public.vehicles v
          WHERE v.id = driver_vehicle_assignments.vehicle_id
            AND public.can_org_admin_write(auth.uid(), v.org_id)
        )
      );

CREATE POLICY "assignments_delete_org_admins"
      ON public.driver_vehicle_assignments FOR DELETE TO authenticated
      USING (
        EXISTS (
          SELECT 1
          FROM public.vehicles v
          WHERE v.id = driver_vehicle_assignments.vehicle_id
            AND public.can_org_admin_write(auth.uid(), v.org_id)
        )
      );

CREATE POLICY "pricing_data_select_same_org_users"
      ON public.pricing_data FOR SELECT TO authenticated
      USING (
        auth.uid() IS NOT NULL
        AND EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.org_id IS NOT NULL)
      );

CREATE POLICY "pricing_data_insert_staff"
      ON public.pricing_data FOR INSERT TO authenticated
      WITH CHECK (public.can_org_admin_write(auth.uid(), (SELECT p.org_id FROM public.profiles p WHERE p.id = auth.uid())));

CREATE POLICY "pricing_data_update_staff"
      ON public.pricing_data FOR UPDATE TO authenticated
      USING (public.can_org_admin_write(auth.uid(), (SELECT p.org_id FROM public.profiles p WHERE p.id = auth.uid())))
      WITH CHECK (public.can_org_admin_write(auth.uid(), (SELECT p.org_id FROM public.profiles p WHERE p.id = auth.uid())));

CREATE POLICY "pricing_data_delete_staff"
      ON public.pricing_data FOR DELETE TO authenticated
      USING (public.can_org_admin_write(auth.uid(), (SELECT p.org_id FROM public.profiles p WHERE p.id = auth.uid())));

CREATE POLICY "procedure6_select_org_users"
      ON public.procedure6_complaints FOR SELECT TO authenticated
      USING (
        auth.uid() IS NOT NULL
        AND EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.org_id IS NOT NULL)
      );

CREATE POLICY "procedure6_insert_staff"
      ON public.procedure6_complaints FOR INSERT TO authenticated
      WITH CHECK (public.can_org_admin_write(auth.uid(), (SELECT p.org_id FROM public.profiles p WHERE p.id = auth.uid())));

CREATE POLICY "procedure6_update_staff"
      ON public.procedure6_complaints FOR UPDATE TO authenticated
      USING (public.can_org_admin_write(auth.uid(), (SELECT p.org_id FROM public.profiles p WHERE p.id = auth.uid())))
      WITH CHECK (public.can_org_admin_write(auth.uid(), (SELECT p.org_id FROM public.profiles p WHERE p.id = auth.uid())));

CREATE POLICY "procedure6_delete_staff"
      ON public.procedure6_complaints FOR DELETE TO authenticated
      USING (public.can_org_admin_write(auth.uid(), (SELECT p.org_id FROM public.profiles p WHERE p.id = auth.uid())));

CREATE POLICY "vehicle_expenses_select_same_org"
      ON public.vehicle_expenses FOR SELECT TO authenticated
      USING (
        EXISTS (
          SELECT 1
          FROM public.vehicles v
          WHERE v.id = vehicle_expenses.vehicle_id
            AND (v.org_id IS NULL OR public.user_belongs_to_org(auth.uid(), v.org_id))
        )
      );

CREATE POLICY "vehicle_expenses_insert_org_admins"
      ON public.vehicle_expenses FOR INSERT TO authenticated
      WITH CHECK (
        EXISTS (
          SELECT 1
          FROM public.vehicles v
          WHERE v.id = vehicle_expenses.vehicle_id
            AND public.can_org_admin_write(auth.uid(), v.org_id)
        )
      );

CREATE POLICY "vehicle_expenses_update_org_admins"
      ON public.vehicle_expenses FOR UPDATE TO authenticated
      USING (
        EXISTS (
          SELECT 1
          FROM public.vehicles v
          WHERE v.id = vehicle_expenses.vehicle_id
            AND public.can_org_admin_write(auth.uid(), v.org_id)
        )
      )
      WITH CHECK (
        EXISTS (
          SELECT 1
          FROM public.vehicles v
          WHERE v.id = vehicle_expenses.vehicle_id
            AND public.can_org_admin_write(auth.uid(), v.org_id)
        )
      );

CREATE POLICY "vehicle_expenses_delete_org_admins"
      ON public.vehicle_expenses FOR DELETE TO authenticated
      USING (
        EXISTS (
          SELECT 1
          FROM public.vehicles v
          WHERE v.id = vehicle_expenses.vehicle_id
            AND public.can_org_admin_write(auth.uid(), v.org_id)
        )
      );

CREATE POLICY "vehicle_incidents_select_same_org"
      ON public.vehicle_incidents FOR SELECT TO authenticated
      USING (
        EXISTS (
          SELECT 1
          FROM public.vehicles v
          WHERE v.id = vehicle_incidents.vehicle_id
            AND (v.org_id IS NULL OR public.user_belongs_to_org(auth.uid(), v.org_id))
        )
      );

CREATE POLICY "vehicle_incidents_insert_org_admins"
      ON public.vehicle_incidents FOR INSERT TO authenticated
      WITH CHECK (
        EXISTS (
          SELECT 1
          FROM public.vehicles v
          WHERE v.id = vehicle_incidents.vehicle_id
            AND public.can_org_admin_write(auth.uid(), v.org_id)
        )
      );

CREATE POLICY "vehicle_incidents_update_org_admins"
      ON public.vehicle_incidents FOR UPDATE TO authenticated
      USING (
        EXISTS (
          SELECT 1
          FROM public.vehicles v
          WHERE v.id = vehicle_incidents.vehicle_id
            AND public.can_org_admin_write(auth.uid(), v.org_id)
        )
      )
      WITH CHECK (
        EXISTS (
          SELECT 1
          FROM public.vehicles v
          WHERE v.id = vehicle_incidents.vehicle_id
            AND public.can_org_admin_write(auth.uid(), v.org_id)
        )
      );

CREATE POLICY "vehicle_incidents_delete_org_admins"
      ON public.vehicle_incidents FOR DELETE TO authenticated
      USING (
        EXISTS (
          SELECT 1
          FROM public.vehicles v
          WHERE v.id = vehicle_incidents.vehicle_id
            AND public.can_org_admin_write(auth.uid(), v.org_id)
        )
      );

CREATE POLICY "vehicle_documents_select_same_org"
      ON public.vehicle_documents FOR SELECT TO authenticated
      USING (
        EXISTS (
          SELECT 1
          FROM public.vehicles v
          WHERE v.id = vehicle_documents.vehicle_id
            AND (v.org_id IS NULL OR public.user_belongs_to_org(auth.uid(), v.org_id))
        )
      );

CREATE POLICY "vehicle_documents_insert_org_admins"
      ON public.vehicle_documents FOR INSERT TO authenticated
      WITH CHECK (
        EXISTS (
          SELECT 1
          FROM public.vehicles v
          WHERE v.id = vehicle_documents.vehicle_id
            AND public.can_org_admin_write(auth.uid(), v.org_id)
        )
      );

CREATE POLICY "vehicle_documents_update_org_admins"
      ON public.vehicle_documents FOR UPDATE TO authenticated
      USING (
        EXISTS (
          SELECT 1
          FROM public.vehicles v
          WHERE v.id = vehicle_documents.vehicle_id
            AND public.can_org_admin_write(auth.uid(), v.org_id)
        )
      )
      WITH CHECK (
        EXISTS (
          SELECT 1
          FROM public.vehicles v
          WHERE v.id = vehicle_documents.vehicle_id
            AND public.can_org_admin_write(auth.uid(), v.org_id)
        )
      );

CREATE POLICY "vehicle_documents_delete_org_admins"
      ON public.vehicle_documents FOR DELETE TO authenticated
      USING (
        EXISTS (
          SELECT 1
          FROM public.vehicles v
          WHERE v.id = vehicle_documents.vehicle_id
            AND public.can_org_admin_write(auth.uid(), v.org_id)
        )
      );

CREATE POLICY "driver_family_members_select_same_org"
        ON public.driver_family_members FOR SELECT TO authenticated
        USING (
          EXISTS (
            SELECT 1 FROM public.drivers d
            WHERE d.id = driver_family_members.driver_id
              AND (d.org_id IS NULL OR public.user_belongs_to_org(auth.uid(), d.org_id))
          )
        );

CREATE POLICY "driver_family_members_insert_org_admins"
        ON public.driver_family_members FOR INSERT TO authenticated
        WITH CHECK (
          EXISTS (
            SELECT 1 FROM public.drivers d
            WHERE d.id = driver_family_members.driver_id
              AND public.can_org_admin_write(auth.uid(), d.org_id)
          )
        );

CREATE POLICY "driver_family_members_update_org_admins"
        ON public.driver_family_members FOR UPDATE TO authenticated
        USING (
          EXISTS (
            SELECT 1 FROM public.drivers d
            WHERE d.id = driver_family_members.driver_id
              AND public.can_org_admin_write(auth.uid(), d.org_id)
          )
        )
        WITH CHECK (
          EXISTS (
            SELECT 1 FROM public.drivers d
            WHERE d.id = driver_family_members.driver_id
              AND public.can_org_admin_write(auth.uid(), d.org_id)
          )
        );

CREATE POLICY "driver_family_members_delete_org_admins"
        ON public.driver_family_members FOR DELETE TO authenticated
        USING (
          EXISTS (
            SELECT 1 FROM public.drivers d
            WHERE d.id = driver_family_members.driver_id
              AND public.can_org_admin_write(auth.uid(), d.org_id)
          )
        );

CREATE POLICY "driver_incidents_select_same_org"
        ON public.driver_incidents FOR SELECT TO authenticated
        USING (
          EXISTS (
            SELECT 1 FROM public.drivers d
            WHERE d.id = driver_incidents.driver_id
              AND (d.org_id IS NULL OR public.user_belongs_to_org(auth.uid(), d.org_id))
          )
        );

CREATE POLICY "driver_incidents_insert_org_admins"
        ON public.driver_incidents FOR INSERT TO authenticated
        WITH CHECK (
          EXISTS (
            SELECT 1 FROM public.drivers d
            WHERE d.id = driver_incidents.driver_id
              AND public.can_org_admin_write(auth.uid(), d.org_id)
          )
        );

CREATE POLICY "driver_incidents_update_org_admins"
        ON public.driver_incidents FOR UPDATE TO authenticated
        USING (
          EXISTS (
            SELECT 1 FROM public.drivers d
            WHERE d.id = driver_incidents.driver_id
              AND public.can_org_admin_write(auth.uid(), d.org_id)
          )
        )
        WITH CHECK (
          EXISTS (
            SELECT 1 FROM public.drivers d
            WHERE d.id = driver_incidents.driver_id
              AND public.can_org_admin_write(auth.uid(), d.org_id)
          )
        );

CREATE POLICY "driver_incidents_delete_org_admins"
        ON public.driver_incidents FOR DELETE TO authenticated
        USING (
          EXISTS (
            SELECT 1 FROM public.drivers d
            WHERE d.id = driver_incidents.driver_id
              AND public.can_org_admin_write(auth.uid(), d.org_id)
          )
        );

CREATE POLICY "mileage_logs_insert_authenticated"
        ON public.mileage_logs FOR INSERT TO authenticated
        WITH CHECK (
          auth.uid() IS NOT NULL
          AND user_id = auth.uid()
          AND EXISTS (
            SELECT 1
            FROM public.vehicles v
            WHERE v.id = mileage_logs.vehicle_id
              AND (v.org_id IS NULL OR public.user_belongs_to_org(auth.uid(), v.org_id))
          )
        );

CREATE POLICY "mileage_logs_select_authenticated"
        ON public.mileage_logs FOR SELECT TO authenticated
        USING (
          EXISTS (
            SELECT 1
            FROM public.vehicles v
            WHERE v.id = mileage_logs.vehicle_id
              AND (v.org_id IS NULL OR public.user_belongs_to_org(auth.uid(), v.org_id))
          )
        );

CREATE POLICY "user_feature_overrides_same_org_staff"
      ON public.user_feature_overrides
      FOR ALL
      TO authenticated
      USING (
        EXISTS (
          SELECT 1
          FROM public.profiles target
          WHERE target.id = user_feature_overrides.user_id
            AND target.org_id IS NOT NULL
            AND public.user_belongs_to_org(auth.uid(), target.org_id)
            AND public.can_org_admin_write(auth.uid(), target.org_id)
        )
      )
      WITH CHECK (
        EXISTS (
          SELECT 1
          FROM public.profiles target
          WHERE target.id = user_feature_overrides.user_id
            AND target.org_id IS NOT NULL
            AND public.user_belongs_to_org(auth.uid(), target.org_id)
            AND public.can_org_admin_write(auth.uid(), target.org_id)
        )
      );
