-- Extracted from full_schema_smart.sql
-- Statements: DO $smart$ blocks (CREATE TYPE), CREATE TABLE, ALTER TABLE — original file order only.
-- Generated by scripts/extract-ddl-tables-alter-type.mjs

DO $smart$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_catalog.pg_type t
    JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace
    WHERE n.nspname = 'public' AND t.typname = 'app_role'
  ) THEN
    CREATE TYPE public.app_role AS ENUM ('admin', 'fleet_manager', 'viewer', 'driver');
  END IF;
END $smart$;

DO $smart$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_catalog.pg_type t
    JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace
    WHERE n.nspname = 'public' AND t.typname = 'compliance_status'
  ) THEN
    CREATE TYPE public.compliance_status AS ENUM ('valid', 'warning', 'expired');
  END IF;
END $smart$;

CREATE TABLE IF NOT EXISTS public.user_roles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    role app_role NOT NULL DEFAULT 'viewer',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    UNIQUE (user_id, role)
);

CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL UNIQUE,
    full_name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.vehicles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    plate_number TEXT NOT NULL UNIQUE,
    manufacturer TEXT NOT NULL,
    model TEXT NOT NULL,
    year INTEGER NOT NULL,
    current_odometer INTEGER NOT NULL DEFAULT 0,
    next_maintenance_km INTEGER,
    next_maintenance_date DATE,
    test_expiry DATE NOT NULL,
    insurance_expiry DATE NOT NULL,
    license_image_url TEXT,
    insurance_pdf_url TEXT,
    status compliance_status NOT NULL DEFAULT 'valid',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.drivers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    full_name TEXT NOT NULL,
    id_number TEXT NOT NULL UNIQUE,
    phone TEXT,
    email TEXT,
    license_expiry DATE NOT NULL,
    health_declaration_date DATE,
    safety_training_date DATE,
    license_front_url TEXT,
    license_back_url TEXT,
    health_declaration_url TEXT,
    status compliance_status NOT NULL DEFAULT 'valid',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.maintenance_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    vehicle_id UUID REFERENCES public.vehicles(id) ON DELETE CASCADE NOT NULL,
    service_date DATE NOT NULL,
    service_type TEXT NOT NULL,
    odometer_reading INTEGER NOT NULL,
    garage_name TEXT,
    cost DECIMAL(10, 2),
    notes TEXT,
    invoice_url TEXT,
    created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.vehicle_handovers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    vehicle_id UUID REFERENCES public.vehicles(id) ON DELETE CASCADE NOT NULL,
    driver_id UUID REFERENCES public.drivers(id) ON DELETE SET NULL,
    handover_type TEXT NOT NULL CHECK (handover_type IN ('delivery', 'return')),
    handover_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    odometer_reading INTEGER NOT NULL,
    fuel_level INTEGER NOT NULL CHECK (fuel_level >= 1 AND fuel_level <= 8),
    photo_front_url TEXT,
    photo_back_url TEXT,
    photo_right_url TEXT,
    photo_left_url TEXT,
    signature_url TEXT,
    notes TEXT,
    created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.compliance_alerts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    entity_type TEXT NOT NULL CHECK (entity_type IN ('vehicle', 'driver')),
    entity_id UUID NOT NULL,
    alert_type TEXT NOT NULL,
    expiry_date DATE NOT NULL,
    status compliance_status NOT NULL DEFAULT 'warning',
    email_sent BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.vehicles ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.drivers ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.maintenance_logs ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.vehicle_handovers ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.compliance_alerts ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.drivers 
ADD COLUMN IF NOT EXISTS address text,
ADD COLUMN IF NOT EXISTS job_title text,
ADD COLUMN IF NOT EXISTS department text,
ADD COLUMN IF NOT EXISTS license_number text,
ADD COLUMN IF NOT EXISTS regulation_585b_date date;

ALTER TABLE public.vehicles 
ADD COLUMN IF NOT EXISTS engine_volume text,
ADD COLUMN IF NOT EXISTS color text,
ADD COLUMN IF NOT EXISTS ignition_code text,
ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS assigned_driver_id uuid REFERENCES public.drivers(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS pickup_date date,
ADD COLUMN IF NOT EXISTS road_ascent_year integer,
ADD COLUMN IF NOT EXISTS road_ascent_month integer,
ADD COLUMN IF NOT EXISTS ownership_type text,
ADD COLUMN IF NOT EXISTS leasing_company_name text,
ADD COLUMN IF NOT EXISTS last_odometer_date date,
ADD COLUMN IF NOT EXISTS manufacturer_code text,
ADD COLUMN IF NOT EXISTS model_code text;

CREATE TABLE IF NOT EXISTS public.driver_documents (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    driver_id uuid NOT NULL REFERENCES public.drivers(id) ON DELETE CASCADE,
    title text NOT NULL,
    file_url text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE public.driver_documents ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.pricing_data (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    manufacturer_code text NOT NULL,
    model_code text NOT NULL,
    usage_value numeric,
    usage_year integer,
    adjusted_price numeric,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    UNIQUE(manufacturer_code, model_code)
);

ALTER TABLE public.pricing_data ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.driver_vehicle_assignments (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  vehicle_id UUID NOT NULL REFERENCES public.vehicles(id) ON DELETE CASCADE,
  driver_id UUID REFERENCES public.drivers(id) ON DELETE SET NULL,
  assigned_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  unassigned_at TIMESTAMP WITH TIME ZONE,
  assigned_by UUID,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE public.driver_vehicle_assignments ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS tax_value_price DECIMAL(10, 2);

ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS tax_value_year INTEGER;

ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS adjusted_price DECIMAL(10, 2);

ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS model_code VARCHAR(50);

ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS chassis_number VARCHAR(100);

ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS average_fuel_consumption DECIMAL(5, 2);

ALTER TABLE public.pricing_data
  ADD COLUMN IF NOT EXISTS registration_year integer,
  ADD COLUMN IF NOT EXISTS vehicle_type_code text,
  ADD COLUMN IF NOT EXISTS manufacturer_name text,
  ADD COLUMN IF NOT EXISTS model_description text,
  ADD COLUMN IF NOT EXISTS fuel_type text,
  ADD COLUMN IF NOT EXISTS commercial_name text,
  ADD COLUMN IF NOT EXISTS is_automatic boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS drive_type text,
  ADD COLUMN IF NOT EXISTS green_score integer,
  ADD COLUMN IF NOT EXISTS pollution_level integer,
  ADD COLUMN IF NOT EXISTS engine_volume_cc integer,
  ADD COLUMN IF NOT EXISTS weight integer,
  ADD COLUMN IF NOT EXISTS list_price numeric,
  ADD COLUMN IF NOT EXISTS effective_date text;

ALTER TABLE public.vehicles
  ADD COLUMN IF NOT EXISTS tax_year integer,
  ADD COLUMN IF NOT EXISTS vehicle_type_code text,
  ADD COLUMN IF NOT EXISTS model_description text,
  ADD COLUMN IF NOT EXISTS fuel_type text,
  ADD COLUMN IF NOT EXISTS commercial_name text,
  ADD COLUMN IF NOT EXISTS is_automatic boolean,
  ADD COLUMN IF NOT EXISTS drive_type text,
  ADD COLUMN IF NOT EXISTS green_score integer,
  ADD COLUMN IF NOT EXISTS pollution_level integer,
  ADD COLUMN IF NOT EXISTS weight integer,
  ADD COLUMN IF NOT EXISTS list_price numeric,
  ADD COLUMN IF NOT EXISTS adjusted_price numeric,
  ADD COLUMN IF NOT EXISTS tax_value_price numeric,
  ADD COLUMN IF NOT EXISTS effective_date text;

ALTER TABLE public.pricing_data DROP CONSTRAINT IF EXISTS pricing_data_manufacturer_code_model_code_key;

ALTER TABLE public.pricing_data ADD CONSTRAINT pricing_data_manufacturer_code_model_code_year_key 
  UNIQUE (manufacturer_code, model_code, registration_year);

ALTER TABLE public.pricing_data DROP CONSTRAINT IF EXISTS pricing_data_manufacturer_code_model_code_year_key;

ALTER TABLE public.drivers ADD COLUMN IF NOT EXISTS driver_code text;

ALTER TABLE public.drivers ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true;

ALTER TABLE public.drivers ADD COLUMN IF NOT EXISTS employee_number text;

ALTER TABLE public.drivers ADD COLUMN IF NOT EXISTS work_start_date date;

ALTER TABLE public.drivers ADD COLUMN IF NOT EXISTS city text;

ALTER TABLE public.drivers ADD COLUMN IF NOT EXISTS note1 text;

ALTER TABLE public.drivers ADD COLUMN IF NOT EXISTS note2 text;

ALTER TABLE public.drivers ADD COLUMN IF NOT EXISTS rating text;

ALTER TABLE public.drivers ADD COLUMN IF NOT EXISTS division text;

ALTER TABLE public.drivers ADD COLUMN IF NOT EXISTS eligibility text;

ALTER TABLE public.drivers ADD COLUMN IF NOT EXISTS area text;

ALTER TABLE public.drivers ADD COLUMN IF NOT EXISTS group_name text;

ALTER TABLE public.drivers ADD COLUMN IF NOT EXISTS group_code text;

ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS chassis_number text;

ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS monthly_total_cost numeric;

ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS sale_date date;

ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS group_name text;

ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS internal_number text;

ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS vehicle_budget numeric;

ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS upgrade_addition numeric;

ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS vehicle_type_name text;

ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS base_index numeric;

ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS driver_code text;

ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS pascal text;

ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS next_alert_km integer;

ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS mandatory_end_date date;

ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS odometer_diff_maintenance numeric;

CREATE TABLE IF NOT EXISTS public.procedure6_complaints (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  vehicle_number TEXT NOT NULL,
  report_id TEXT,
  report_type TEXT,
  location TEXT,
  description TEXT,
  report_date_time TIMESTAMPTZ,
  reporter_name TEXT,
  reporter_cell_phone TEXT,
  received_time TIMESTAMPTZ,
  receiver_name TEXT,
  driver_response TEXT,
  driver_name TEXT,
  action_taken TEXT,
  first_update_time TIMESTAMPTZ,
  last_update_time TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'open',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.procedure6_complaints ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.vehicle_handovers
ADD COLUMN IF NOT EXISTS assignment_mode text NOT NULL DEFAULT 'permanent'
CHECK (assignment_mode IN ('permanent', 'replacement'));

CREATE TABLE IF NOT EXISTS public.vehicle_documents (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    vehicle_id uuid NOT NULL REFERENCES public.vehicles(id) ON DELETE CASCADE,
    handover_id uuid REFERENCES public.vehicle_handovers(id) ON DELETE SET NULL,
    title text NOT NULL,
    file_url text NOT NULL,
    document_type text NOT NULL DEFAULT 'handover',
    metadata jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE public.vehicle_documents ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.vehicle_handovers
ADD COLUMN IF NOT EXISTS pdf_url text;

create table if not exists public.system_settings (
  key        text        primary key,
  value      jsonb       not null default '{}',
  updated_at timestamptz not null default now()
);

alter table public.system_settings enable row level security;

ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS purchase_date date;

CREATE TABLE IF NOT EXISTS public.organization_settings (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_name              text NOT NULL DEFAULT '',
  org_id_number         text NOT NULL DEFAULT '',
  admin_email           text NOT NULL DEFAULT '',
  health_statement_text text NOT NULL DEFAULT '',
  vehicle_policy_text   text NOT NULL DEFAULT '',
  updated_at            timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.organization_settings ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.organization_settings
  ADD COLUMN IF NOT EXISTS health_statement_pdf_url  text,
  ADD COLUMN IF NOT EXISTS vehicle_policy_pdf_url   text;

CREATE TABLE IF NOT EXISTS public.ui_customization (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key           text UNIQUE NOT NULL,
  default_label text NOT NULL,
  custom_label  text NOT NULL DEFAULT '',
  updated_at    timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.ui_customization ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.org_documents (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title               text NOT NULL,
  description         text NOT NULL DEFAULT '',
  file_url            text,
  include_in_handover boolean NOT NULL DEFAULT false,
  is_standalone       boolean NOT NULL DEFAULT false,
  requires_signature  boolean NOT NULL DEFAULT true,
  sort_order          integer NOT NULL DEFAULT 0,
  is_active           boolean NOT NULL DEFAULT true,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.org_documents ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.ui_customization
  ADD COLUMN IF NOT EXISTS is_visible  boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS group_name  text    NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS public.vehicle_expenses (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vehicle_id    uuid NOT NULL REFERENCES public.vehicles(id) ON DELETE CASCADE,
  expense_date  date NOT NULL,
  category      text NOT NULL DEFAULT 'other',
  description   text NOT NULL DEFAULT '',
  amount        numeric(10,2) NOT NULL DEFAULT 0,
  supplier      text,
  invoice_url   text,
  notes         text,
  created_by    uuid REFERENCES auth.users(id),
  created_at    timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.vehicle_expenses ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.vehicle_incidents (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vehicle_id       uuid NOT NULL REFERENCES public.vehicles(id) ON DELETE CASCADE,
  incident_type    text NOT NULL DEFAULT 'event',  -- 'event' | 'accident'
  incident_date    date NOT NULL,
  description      text NOT NULL DEFAULT '',
  location         text,
  driver_id        uuid REFERENCES public.drivers(id),
  damage_desc      text,
  photo_urls       text[],
  police_report_no text,
  insurance_claim  text,
  status           text NOT NULL DEFAULT 'open',   -- 'open' | 'closed'
  notes            text,
  created_by       uuid REFERENCES auth.users(id),
  created_at       timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.vehicle_incidents ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.vehicles
  ADD COLUMN IF NOT EXISTS last_service_date      date,
  ADD COLUMN IF NOT EXISTS last_service_km        integer,
  ADD COLUMN IF NOT EXISTS last_tire_change_date  date,
  ADD COLUMN IF NOT EXISTS next_tire_change_date  date,
  ADD COLUMN IF NOT EXISTS last_inspection_date   date,
  ADD COLUMN IF NOT EXISTS next_inspection_date   date;

ALTER TABLE drivers
  ADD COLUMN IF NOT EXISTS birth_date date,
  ADD COLUMN IF NOT EXISTS family_permit_date date,
  ADD COLUMN IF NOT EXISTS driving_permit text,
  ADD COLUMN IF NOT EXISTS is_field_person boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS practical_driving_test_date date;

CREATE TABLE IF NOT EXISTS driver_family_members (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  driver_id       uuid NOT NULL REFERENCES drivers(id) ON DELETE CASCADE,
  full_name       text NOT NULL,
  relationship    text NOT NULL,          -- spouse / child / parent / sibling / other
  phone           text,
  id_number       text,
  birth_date      date,
  address         text,
  city            text,
  notes           text,
  created_at      timestamptz DEFAULT now()
);

ALTER TABLE driver_family_members ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS driver_incidents (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  driver_id           uuid NOT NULL REFERENCES drivers(id) ON DELETE CASCADE,
  vehicle_id          uuid REFERENCES vehicles(id) ON DELETE SET NULL,
  incident_type       text NOT NULL CHECK (incident_type IN ('event', 'accident')),
  incident_date       date NOT NULL,
  description         text NOT NULL,
  location            text,
  damage_desc         text,
  police_report_no    text,
  insurance_claim     text,
  photo_urls          text[],
  status              text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed')),
  notes               text,
  created_at          timestamptz DEFAULT now()
);

ALTER TABLE driver_incidents ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.org_documents
  ADD COLUMN IF NOT EXISTS category text NOT NULL DEFAULT 'תפעול',
  ADD COLUMN IF NOT EXISTS json_schema jsonb,
  ADD COLUMN IF NOT EXISTS autofill_fields text[] NOT NULL DEFAULT ARRAY[]::text[];

ALTER TABLE public.org_documents
  ADD COLUMN IF NOT EXISTS include_in_delivery boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS include_in_return boolean NOT NULL DEFAULT false;

ALTER TABLE public.vehicles
  ADD COLUMN IF NOT EXISTS tire_change_date_front_right date,
  ADD COLUMN IF NOT EXISTS tire_change_date_front_left  date,
  ADD COLUMN IF NOT EXISTS tire_change_date_rear_right  date,
  ADD COLUMN IF NOT EXISTS tire_change_date_rear_left   date,
  ADD COLUMN IF NOT EXISTS inspection_form_url          text;

ALTER TABLE public.organization_settings
  ADD COLUMN IF NOT EXISTS organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE;

ALTER TABLE public.vehicles
  ADD COLUMN IF NOT EXISTS org_id uuid REFERENCES public.organizations(id) ON DELETE SET NULL;

ALTER TABLE public.drivers
  ADD COLUMN IF NOT EXISTS org_id uuid REFERENCES public.organizations(id) ON DELETE SET NULL;

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS permissions jsonb DEFAULT NULL;

CREATE TABLE IF NOT EXISTS public.org_invitations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  email text NOT NULL,
  permissions jsonb DEFAULT '{}',
  invited_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(org_id, email)
);

ALTER TABLE public.org_invitations ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS org_id uuid REFERENCES public.organizations(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS public.org_members (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, org_id)
);

ALTER TABLE public.org_members ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'pending_approval'
  CHECK (status IN ('pending_approval', 'active'));

ALTER TABLE public.profiles
  ALTER COLUMN status SET DEFAULT 'pending_approval';

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS parent_admin_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL;

ALTER TABLE public.org_documents
  ADD COLUMN IF NOT EXISTS name text;

ALTER TABLE public.organizations
  ADD COLUMN IF NOT EXISTS release_snapshot_ack_version TEXT NOT NULL DEFAULT '0.0.0';

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS allowed_features jsonb;

ALTER TABLE public.vehicles
  ADD COLUMN IF NOT EXISTS managed_by_user_id uuid REFERENCES public.profiles (id) ON DELETE SET NULL;

ALTER TABLE public.drivers
  ADD COLUMN IF NOT EXISTS managed_by_user_id uuid REFERENCES public.profiles (id) ON DELETE SET NULL;

ALTER TABLE public.user_feature_overrides ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS managed_by_user_id uuid REFERENCES public.profiles (id) ON DELETE SET NULL;

alter table public.vehicles
  add column if not exists service_interval_km integer null;

alter table public.mileage_logs enable row level security;

CREATE TABLE IF NOT EXISTS public.ui_settings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  org_name text NOT NULL DEFAULT '',
  org_id_number text NOT NULL DEFAULT '',
  admin_email text NOT NULL DEFAULT '',
  health_statement_text text NOT NULL DEFAULT '',
  vehicle_policy_text text NOT NULL DEFAULT '',
  health_statement_pdf_url text,
  vehicle_policy_pdf_url text,
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.ui_settings
  ADD COLUMN IF NOT EXISTS health_statement_pdf_url text;

ALTER TABLE public.ui_settings
  ADD COLUMN IF NOT EXISTS vehicle_policy_pdf_url text;

ALTER TABLE public.ui_settings ENABLE ROW LEVEL SECURITY;
