import type { FleetColumnOption } from '@/components/fleet/FleetTableColumnsSheet';

/** עמודות אופציונליות (ללא צ׳קבוקס, מספר רישוי ותפריט פעולות) */
export const VEHICLE_HUD_OPTIONAL_COLUMNS: FleetColumnOption[] = [
  { id: 'vehicle_type', label: 'סוג רכב' },
  { id: 'assigned_driver', label: 'נהג משויך' },
  { id: 'compliance', label: 'סטטוס (טסט / ביטוח)' },
  { id: 'ownership', label: 'בעלות' },
  { id: 'odometer', label: 'ק״מ נוכחי' },
  { id: 'is_active', label: 'פעיל / לא פעיל' },
  { id: 'test_expiry', label: 'תוקף טסט' },
  { id: 'insurance_expiry', label: 'תוקף ביטוח' },
  { id: 'monthly_total_cost', label: 'עלות ליסינג חודשית' },
  { id: 'tax_value_price', label: 'שווי מס' },
  { id: 'last_odometer_date', label: 'תאריך ק״מ אחרון' },
  { id: 'year', label: 'שנת ייצור' },
  { id: 'road_ascent', label: 'עלייה לכביש (חודש/שנה)' },
  { id: 'manufacturer', label: 'יצרן' },
  { id: 'model', label: 'דגם' },
  { id: 'color', label: 'צבע' },
  { id: 'fuel_type', label: 'סוג דלק' },
  { id: 'group_name', label: 'קבוצה' },
  { id: 'chassis_number', label: 'מספר שלדה' },
  { id: 'driver_code', label: 'קוד נהג (ברכב)' },
  { id: 'safety_officer', label: 'קצין בטיחות' },
  { id: 'vat_recognized', label: 'מע״מ מוכר' },
  { id: 'base_index', label: 'מדד בסיס' },
  { id: 'vehicle_standard', label: 'תקן רכב' },
  { id: 'leasing_company_name', label: 'חברת ליסינג' },
  { id: 'internal_number', label: 'מספר פנימי' },
  { id: 'next_maintenance_km', label: 'ק״מ טיפול הבא' },
  { id: 'last_service_date', label: 'תאריך טיפול אחרון' },
  { id: 'pickup_date', label: 'תאריך קליטה' },
  { id: 'purchase_date', label: 'תאריך קניה' },
  { id: 'sale_date', label: 'תאריך מכירה' },
  { id: 'engine_volume', label: 'נפח מנוע' },
  { id: 'ignition_code', label: 'קוד הנעה' },
  { id: 'next_maintenance_date', label: 'תאריך טיפול הבא' },
  { id: 'last_service_km', label: 'ק״מ טיפול אחרון' },
  { id: 'service_interval_km', label: 'מרווח טיפול (ק״מ)' },
  { id: 'average_fuel_consumption', label: 'צריכת דלק ממוצעת' },
  { id: 'tax_year', label: 'שנת מס' },
  { id: 'adjusted_price', label: 'מחיר מותאם' },
  { id: 'vehicle_budget', label: 'תקציב רכב' },
  { id: 'upgrade_addition', label: 'תוספת שדרוג' },
  { id: 'mandatory_end_date', label: 'תאריך סיום חובה' },
  { id: 'last_tire_change_date', label: 'החלפת צמיגים אחרונה' },
  { id: 'next_tire_change_date', label: 'החלפת צמיגים הבאה' },
];

export const VEHICLE_HUD_OPTIONAL_IDS = VEHICLE_HUD_OPTIONAL_COLUMNS.map((c) => c.id);

export const DEFAULT_VEHICLE_HUD_OPTIONAL_VISIBLE = [
  'vehicle_type',
  'assigned_driver',
  'compliance',
  'ownership',
  'odometer',
] as const;
